// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import Car4 from "../../public/model_3d/Car/Car1/ford_mustang.glb"
export default function ModelCar4(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, Car4)

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_361_0" position={[0, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Material']} geometry={nodes['Object_4'].geometry} name="Object_4" />
              </group>
              <group name="Object_362_1" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_02']} geometry={nodes['Object_6'].geometry} name="Object_6" />
              </group>
              <group name="Sandogh_Agha_2" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_8'].geometry} name="Object_8" />
                <mesh material={materials['Color_04.001']} geometry={nodes['Object_9'].geometry} name="Object_9" />
              </group>
              <group name="Object_364_3" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Miror']} geometry={nodes['Object_11'].geometry} name="Object_11" />
                <mesh material={materials['Black']} geometry={nodes['Object_12'].geometry} name="Object_12" />
              </group>
              <group name="Object_367_4" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['interior']} geometry={nodes['Object_14'].geometry} name="Object_14" />
              </group>
              <group name="Object_368_5" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Glass']} geometry={nodes['Object_16'].geometry} name="Object_16" />
              </group>
              <group name="Front_light10_6" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['black1']} geometry={nodes['Object_18'].geometry} name="Object_18" />
              </group>
              <group name="Kapoot_7" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_20'].geometry} name="Object_20" />
                <mesh material={materials['Color_04.001']} geometry={nodes['Object_21'].geometry} name="Object_21" />
              </group>
              <group name="Object_122_8" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_23'].geometry} name="Object_23" />
              </group>
              <group name="Back_Side_9" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_25'].geometry} name="Object_25" />
              </group>
              <group name="Back_Side_Roosh_10" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_27'].geometry} name="Object_27" />
              </group>
              <group name="Up_tires_11" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_02']} geometry={nodes['Object_29'].geometry} name="Object_29" />
              </group>
              <group name="Exus_12" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Material.012']} geometry={nodes['Object_31'].geometry} name="Object_31" />
              </group>
              <group name="Object_152_13" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['tail_lig']} geometry={nodes['Object_33'].geometry} name="Object_33" />
                <mesh material={materials['Back_main_Light']} geometry={nodes['Object_34'].geometry} name="Object_34" />
              </group>
              <group name="Object_154_14" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['tail_lig']} geometry={nodes['Object_36'].geometry} name="Object_36" />
                <mesh material={materials['Back_main_Light']} geometry={nodes['Object_37'].geometry} name="Object_37" />
              </group>
              <group name="Object_156_15" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['tail_lig']} geometry={nodes['Object_39'].geometry} name="Object_39" />
                <mesh material={materials['Back_main_Light']} geometry={nodes['Object_40'].geometry} name="Object_40" />
              </group>
              <group name="Object_159_16" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_42'].geometry} name="Object_42" />
              </group>
              <group name="Object_172_17" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_44'].geometry} name="Object_44" />
              </group>
              <group name="Object_177_19" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_46'].geometry} name="Object_46" />
              </group>
              <group name="Miror1001_20" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Miror']} geometry={nodes['Object_49'].geometry} name="Object_49" />
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_48'].geometry} name="Object_48" />
              </group>
              <group name="Object_191_21" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_51'].geometry} name="Object_51" />
              </group>
              <group name="Rooye_Kapoot_22" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_53'].geometry} name="Object_53" />
              </group>
              <group name="Front_light11_23" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_55'].geometry} name="Object_55" />
                <mesh material={materials['Color_04.001']} geometry={nodes['Object_56'].geometry} name="Object_56" />
              </group>
              <group name="Front_light7_&_lockdoor_24" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_58'].geometry} name="Object_58" />
              </group>
              <group name="Object_236_25" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['grille1']} geometry={nodes['Object_60'].geometry} name="Object_60" />
              </group>
              <group name="Object_237_26" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_02']} geometry={nodes['Object_62'].geometry} name="Object_62" />
              </group>
              <group name="Object_238_27" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_03']} geometry={nodes['Object_64'].geometry} name="Object_64" />
              </group>
              <group name="Front_light9_28" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['textured']} geometry={nodes['Object_66'].geometry} name="Object_66" />
                <mesh material={materials['Front_light']} geometry={nodes['Object_67'].geometry} name="Object_67" />
              </group>
              <group name="Object_202_29" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_69'].geometry} name="Object_69" />
              </group>
              <group name="Object_203_30" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_71'].geometry} name="Object_71" />
              </group>
              <group name="Object_205_31" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['material_0']} geometry={nodes['Object_73'].geometry} name="Object_73" />
              </group>
              <group name="Object_206_32" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_back']} geometry={nodes['Object_75'].geometry} name="Object_75" />
              </group>
              <group name="Front_light8_33" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Glass']} geometry={nodes['Object_77'].geometry} name="Object_77" />
              </group>
              <group name="Object_212_34" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_79'].geometry} name="Object_79" />
              </group>
              <group name="Object_218_35" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_81'].geometry} name="Object_81" />
              </group>
              <group name="Object_223_36" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_83'].geometry} name="Object_83" />
              </group>
              <group name="Object_224_37" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['FrontCol']} geometry={nodes['Object_85'].geometry} name="Object_85" />
              </group>
              <group name="Object_235_38" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_87'].geometry} name="Object_87" />
              </group>
              <group name="Object_230_39" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Material.010']} geometry={nodes['Object_89'].geometry} name="Object_89" />
              </group>
              <group name="Front_light4_40" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['detail01']} geometry={nodes['Object_91'].geometry} name="Object_91" />
              </group>
              <group name="Object_233_41" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_93'].geometry} name="Object_93" />
              </group>
              <group name="Object_240_42" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_95'].geometry} name="Object_95" />
              </group>
              <group name="Object_241_43" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['FrontCol']} geometry={nodes['Object_97'].geometry} name="Object_97" />
              </group>
              <group name="Object_242_44" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Material.023']} geometry={nodes['Object_99'].geometry} name="Object_99" />
              </group>
              <group name="Object_245_45" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_101'].geometry} name="Object_101" />
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_103'].geometry} name="Object_103" />
                <mesh
                  material={materials['interior_brown']}
                  geometry={nodes['Object_102'].geometry}
                  name="Object_102"
                />
                <mesh material={materials['Material.004']} geometry={nodes['Object_104'].geometry} name="Object_104" />
              </group>
              <group name="Front_light6_46" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['textur01']} geometry={nodes['Object_106'].geometry} name="Object_106" />
                <mesh material={materials['Material.005']} geometry={nodes['Object_107'].geometry} name="Object_107" />
              </group>
              <group name="Object_251_49" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['material_0']} geometry={nodes['Object_109'].geometry} name="Object_109" />
              </group>
              <group name="Object_265_50" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_111'].geometry} name="Object_111" />
                <mesh material={materials['Color_04.001']} geometry={nodes['Object_112'].geometry} name="Object_112" />
              </group>
              <group name="Object_267_51" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_114'].geometry} name="Object_114" />
              </group>
              <group name="Object_270_52" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_116'].geometry} name="Object_116" />
              </group>
              <group name="Back_Pahloo_53" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_118'].geometry} name="Object_118" />
              </group>
              <group name="Object_295_54" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_120'].geometry} name="Object_120" />
              </group>
              <group name="Object_296_55" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_122'].geometry} name="Object_122" />
                <mesh material={materials['Color_04.001']} geometry={nodes['Object_123'].geometry} name="Object_123" />
              </group>
              <group name="Object_299_56" rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
                <mesh material={materials['bbea21f7']} geometry={nodes['Object_125'].geometry} name="Object_125" />
              </group>
              <group name="Object_274_57" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_127'].geometry} name="Object_127" />
              </group>
              <group name="Object_275_58" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_129'].geometry} name="Object_129" />
              </group>
              <group name="Object_281_59" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_131'].geometry} name="Object_131" />
              </group>
              <group name="Object_282_60" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_133'].geometry} name="Object_133" />
              </group>
              <group name="Object_283_61" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_135'].geometry} name="Object_135" />
              </group>
              <group name="Object_278_62" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_137'].geometry} name="Object_137" />
              </group>
              <group name="Object_280_63" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_139'].geometry} name="Object_139" />
                <mesh material={materials['textur01']} geometry={nodes['Object_140'].geometry} name="Object_140" />
              </group>
              <group name="Object_285_64" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_142'].geometry} name="Object_142" />
              </group>
              <group name="Object_292_65" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_144'].geometry} name="Object_144" />
              </group>
              <group name="Front_light5_66" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['detail02']} geometry={nodes['Object_146'].geometry} name="Object_146" />
              </group>
              <group name="Front_light_67" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_back']} geometry={nodes['Object_149'].geometry} name="Object_149" />
                <mesh material={materials['head_lig']} geometry={nodes['Object_148'].geometry} name="Object_148" />
                <mesh material={materials['Head_Light']} geometry={nodes['Object_150'].geometry} name="Object_150" />
              </group>
              <group name="Front_light2_68" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Glass']} geometry={nodes['Object_152'].geometry} name="Object_152" />
              </group>
              <group name="Object_311_69" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_00']} geometry={nodes['Object_154'].geometry} name="Object_154" />
              </group>
              <group name="Object_315_70" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_156'].geometry} name="Object_156" />
              </group>
              <group name="Object_316_71" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_158'].geometry} name="Object_158" />
              </group>
              <group name="Object_319_72" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_160'].geometry} name="Object_160" />
              </group>
              <group name="Object_320_73" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_162'].geometry} name="Object_162" />
              </group>
              <group name="Front_light3_74" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['detail01']} geometry={nodes['Object_164'].geometry} name="Object_164" />
              </group>
              <group name="Object_326_75" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_166'].geometry} name="Object_166" />
                <mesh material={materials['Material.009']} geometry={nodes['Object_167'].geometry} name="Object_167" />
                <mesh material={materials['logo_farmoon']} geometry={nodes['Object_168'].geometry} name="Object_168" />
              </group>
              <group name="Object_328_76" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_170'].geometry} name="Object_170" />
              </group>
              <group name="Object_334_77" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_173'].geometry} name="Object_173" />
                <mesh material={materials['Color_00']} geometry={nodes['Object_172'].geometry} name="Object_172" />
              </group>
              <group name="Object_332_78" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_175'].geometry} name="Object_175" />
              </group>
              <group name="Object_333_79" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_177'].geometry} name="Object_177" />
              </group>
              <group name="Separ_Jelo_80" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_179'].geometry} name="Object_179" />
              </group>
              <group name="Object_340_81" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_back']} geometry={nodes['Object_181'].geometry} name="Object_181" />
              </group>
              <group name="Object_343_82" position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_183'].geometry} name="Object_183" />
              </group>
              <group name="Object_347_83" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_185'].geometry} name="Object_185" />
              </group>
              <group name="Object_349_84" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_187'].geometry} name="Object_187" />
              </group>
              <group name="Object_350_85" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_02']} geometry={nodes['Object_189'].geometry} name="Object_189" />
              </group>
              <group name="Object_352_86" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_191'].geometry} name="Object_191" />
              </group>
              <group name="Object_353_87" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_193'].geometry} name="Object_193" />
              </group>
              <group name="Object_356_88" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Foregrou']} geometry={nodes['Object_195'].geometry} name="Object_195" />
              </group>
              <group name="Anten_89" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_197'].geometry} name="Object_197" />
              </group>
              <group name="Barf_Pakon_90" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_00']} geometry={nodes['Object_199'].geometry} name="Object_199" />
              </group>
              <group name="Zir_Barfpakon_91" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_02']} geometry={nodes['Object_201'].geometry} name="Object_201" />
              </group>
              <group name="Door_lock1_93" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Color_04']} geometry={nodes['Object_203'].geometry} name="Object_203" />
              </group>
              <group name="Miror1_94" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_205'].geometry} name="Object_205" />
              </group>
              <group name="Dande_$_Farmoon_95" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Black']} geometry={nodes['Object_207'].geometry} name="Object_207" />
              </group>
              <group name="Cooler__96" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_209'].geometry} name="Object_209" />
              </group>
              <group name="Cooler_001_97" position={[0.16, 0.09, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Glass']} geometry={nodes['Object_212'].geometry} name="Object_212" />
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_211'].geometry} name="Object_211" />
                <mesh material={materials['1_analog']} geometry={nodes['Object_213'].geometry} name="Object_213" />
                <mesh material={materials['2_analog']} geometry={nodes['Object_214'].geometry} name="Object_214" />
                <mesh material={materials['3_analog']} geometry={nodes['Object_215'].geometry} name="Object_215" />
                <mesh material={materials['4_analog']} geometry={nodes['Object_216'].geometry} name="Object_216" />
                <mesh material={materials['5_analog']} geometry={nodes['Object_217'].geometry} name="Object_217" />
              </group>
              <group name="Object_245001_98" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Carpet']} geometry={nodes['Object_219'].geometry} name="Object_219" />
              </group>
              <group name="Disk_Breake_Front_99" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['material']} geometry={nodes['Object_221'].geometry} name="Object_221" />
              </group>
              <group name="Ring_Sport_Front_100" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['Material.018']} geometry={nodes['Object_223'].geometry} name="Object_223" />
                <mesh material={materials['Material.008']} geometry={nodes['Object_224'].geometry} name="Object_224" />
              </group>
              <group name="Tire_Front_101" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh material={materials['2011_06']} geometry={nodes['Object_226'].geometry} name="Object_226" />
                <mesh material={materials['bfgoodri']} geometry={nodes['Object_227'].geometry} name="Object_227" />
              </group>
              <group name="Plane002_102" position={[0.16, 0.11, 0.08]} rotation={[0, 0, 0]} scale={[0.09, 0.09, 0.16]}>
                <mesh material={materials['Carpet']} geometry={nodes['Object_229'].geometry} name="Object_229" />
              </group>
              <group name="Plane003_103" position={[-0.16, 0.11, 0.08]} rotation={[0, 0, 0]} scale={[0.09, 0.09, 0.16]}>
                <mesh material={materials['Carpet']} geometry={nodes['Object_231'].geometry} name="Object_231" />
              </group>
              <group
                name="Ford_Logo_104"
                position={[0, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.11, 0.11, 0.11]}>
                <mesh material={materials['Logo_Ford']} geometry={nodes['Object_233'].geometry} name="Object_233" />
              </group>
              <group name="Plane_105">
                <mesh material={materials['Black']} geometry={nodes['Object_235'].geometry} name="Object_235" />
                <mesh material={materials['Glass']} geometry={nodes['Object_236'].geometry} name="Object_236" />
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_237'].geometry} name="Object_237" />
              </group>
              <group name="Cylinder_106" position={[0, 0.21, 0.16]} scale={[0, 0, 0]}>
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_239'].geometry} name="Object_239" />
              </group>
              <group
                name="Plane001_107"
                position={[0.11, 0.15, 0.28]}
                rotation={[-1.03, 0, 0]}
                scale={[0.01, 0.03, 0.03]}>
                <mesh material={materials['Black']} geometry={nodes['Object_241'].geometry} name="Object_241" />
                <mesh material={materials['Metal_Part']} geometry={nodes['Object_242'].geometry} name="Object_242" />
              </group>
              <group name="BezierCurve_108" position={[0.47, 0, 0]} rotation={[0, 0, 1.6]} scale={[0.13, 0.13, 0.13]}>
                <mesh material={materials['Material.002']} geometry={nodes['Object_244'].geometry} name="Object_244" />
              </group>
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
