// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import Car2 from "../../public/model_3d/Car/Car1/lambor_revuelto.glb"
export default function ModelCar2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, Car2)

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Lamborghini_revueltofbx" rotation={[-Math.PI, 0, 0]} scale={[0.01, 0.01, 0.01]}>
            <group name="RootNode">
              <group name="Front_part_6" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Front_part_6_Carbon_0'].geometry}
                  name="Front_part_6_Carbon_0"
                />
              </group>
              <group name="Daylight_Part" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Daylight_Part_Carbon_0'].geometry}
                  name="Daylight_Part_Carbon_0"
                />
                <mesh
                  material={materials['Inside_Headlight']}
                  geometry={nodes['Daylight_Part_Inside_Headlight_0'].geometry}
                  name="Daylight_Part_Inside_Headlight_0"
                />
              </group>
              <group name="Daylight_Glass" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Headlight_glass.001']}
                  geometry={nodes['Daylight_Glass_Headlight_glass001_0'].geometry}
                  name="Daylight_Glass_Headlight_glass001_0"
                />
              </group>
              <group name="Daylight" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Light']}
                  geometry={nodes['Daylight_Light_0'].geometry}
                  name="Daylight_Light_0"
                />
              </group>
              <group name="Tail_light" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Taillight_glass']}
                  geometry={nodes['Tail_light_Taillight_glass_0'].geometry}
                  name="Tail_light_Taillight_glass_0"
                />
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Tail_light_Plastic_0'].geometry}
                  name="Tail_light_Plastic_0"
                />
                <mesh
                  material={materials['Tail_light']}
                  geometry={nodes['Tail_light_Tail_light_0'].geometry}
                  name="Tail_light_Tail_light_0"
                />
              </group>
              <group name="Rear_plastic_part_1" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_plastic_part_1_Plastic_0'].geometry}
                  name="Rear_plastic_part_1_Plastic_0"
                />
              </group>
              <group name="Exhaust_1" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Exhaust_1_Plastic_0'].geometry}
                  name="Exhaust_1_Plastic_0"
                />
                <mesh
                  material={materials['Exhaust']}
                  geometry={nodes['Exhaust_1_Exhaust_0'].geometry}
                  name="Exhaust_1_Exhaust_0"
                />
              </group>
              <group name="Rear_part_4" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_4_Plastic_0'].geometry}
                  name="Rear_part_4_Plastic_0"
                />
              </group>
              <group name="Rear_part_3" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_3_Plastic_0'].geometry}
                  name="Rear_part_3_Plastic_0"
                />
              </group>
              <group name="Rear_part_6" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_6_Plastic_0'].geometry}
                  name="Rear_part_6_Plastic_0"
                />
              </group>
              <group name="Rear_vent" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Vents']}
                  geometry={nodes['Rear_vent_Vents_0'].geometry}
                  name="Rear_vent_Vents_0"
                />
              </group>
              <group name="Rear_part_1" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_1_Plastic_0'].geometry}
                  name="Rear_part_1_Plastic_0"
                />
              </group>
              <group name="Rear_part_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_2_Plastic_0'].geometry}
                  name="Rear_part_2_Plastic_0"
                />
              </group>
              <group name="Rear_engine_carbon" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Rear_engine_carbon_Carbon_0'].geometry}
                  name="Rear_engine_carbon_Carbon_0"
                />
                <mesh
                  material={materials['Vents']}
                  geometry={nodes['Rear_engine_carbon_Vents_0'].geometry}
                  name="Rear_engine_carbon_Vents_0"
                />
              </group>
              <group name="Rear_plastic" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_plastic_Plastic_0'].geometry}
                  name="Rear_plastic_Plastic_0"
                />
              </group>
              <group name="Vents_rear" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Vents']}
                  geometry={nodes['Vents_rear_Vents_0'].geometry}
                  name="Vents_rear_Vents_0"
                />
              </group>
              <group name="Engine" rotation={[0, 0, -Math.PI / 2]} scale={[100, 94.04, 100]}>
                <mesh
                  material={materials['Engine']}
                  geometry={nodes['Engine_Engine_0'].geometry}
                  name="Engine_Engine_0"
                />
              </group>
              <group name="Front_part_9" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_9_Plastic_0'].geometry}
                  name="Front_part_9_Plastic_0"
                />
                <mesh
                  material={materials['Sphere']}
                  geometry={nodes['Front_part_9_Sphere_0'].geometry}
                  name="Front_part_9_Sphere_0"
                />
              </group>
              <group name="Front_vents" rotation={[0, 0, -Math.PI / 2]} scale={[100, 94.04, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_vents_Plastic_0'].geometry}
                  name="Front_vents_Plastic_0"
                />
              </group>
              <group name="Front_part_7" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_7_Plastic_0'].geometry}
                  name="Front_part_7_Plastic_0"
                />
              </group>
              <group name="Front_part_8001" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_8001_Plastic_0'].geometry}
                  name="Front_part_8001_Plastic_0"
                />
                <mesh
                  material={materials['Sphere']}
                  geometry={nodes['Front_part_8001_Sphere_0'].geometry}
                  name="Front_part_8001_Sphere_0"
                />
              </group>
              <group name="Front_part_4" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Front_part_4_Carbon_0'].geometry}
                  name="Front_part_4_Carbon_0"
                />
              </group>
              <group name="Front_part_1" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_1_Plastic_0'].geometry}
                  name="Front_part_1_Plastic_0"
                />
                <mesh
                  material={materials['Metal']}
                  geometry={nodes['Front_part_1_Metal_0'].geometry}
                  name="Front_part_1_Metal_0"
                />
              </group>
              <group name="Front_part_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_2_Plastic_0'].geometry}
                  name="Front_part_2_Plastic_0"
                />
              </group>
              <group name="Front_part_3" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_3_Plastic_0'].geometry}
                  name="Front_part_3_Plastic_0"
                />
              </group>
              <group name="Front_vents_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Vents']}
                  geometry={nodes['Front_vents_2_Vents_0'].geometry}
                  name="Front_vents_2_Vents_0"
                />
              </group>
              <group name="Rear_part_5" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Rear_part_5_Plastic_0'].geometry}
                  name="Rear_part_5_Plastic_0"
                />
              </group>
              <group name="Front_part_8" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_8_Plastic_0'].geometry}
                  name="Front_part_8_Plastic_0"
                />
              </group>
              <group name="Front_part_5" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Front_part_5_Plastic_0'].geometry}
                  name="Front_part_5_Plastic_0"
                />
              </group>
              <group name="Headlight_carbon" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Headlight_carbon_Carbon_0'].geometry}
                  name="Headlight_carbon_Carbon_0"
                />
              </group>
              <group name="Headlight" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Headlight']}
                  geometry={nodes['Headlight_Headlight_0'].geometry}
                  name="Headlight_Headlight_0"
                />
                <mesh
                  material={materials['Headlight_ligh_second']}
                  geometry={nodes['Headlight_Headlight_ligh_second_0'].geometry}
                  name="Headlight_Headlight_ligh_second_0"
                />
                <mesh
                  material={materials['Headlight_light']}
                  geometry={nodes['Headlight_Headlight_light_0'].geometry}
                  name="Headlight_Headlight_light_0"
                />
              </group>
              <group name="Headlight_glass" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Headlight_glass']}
                  geometry={nodes['Headlight_glass_Headlight_glass_0'].geometry}
                  name="Headlight_glass_Headlight_glass_0"
                />
              </group>
              <group name="Exhaust_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Exhaust_2_Plastic_0'].geometry}
                  name="Exhaust_2_Plastic_0"
                />
              </group>
              <group name="Vents" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Vents_Carbon_0'].geometry}
                  name="Vents_Carbon_0"
                />
                <mesh material={materials['Vents']} geometry={nodes['Vents_Vents_0'].geometry} name="Vents_Vents_0" />
              </group>
              <group name="Mid_part_3001" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Mid_part_3001_Carbon_0'].geometry}
                  name="Mid_part_3001_Carbon_0"
                />
              </group>
              <group name="Windshield" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Windows']}
                  geometry={nodes['Windshield_Windows_0'].geometry}
                  name="Windshield_Windows_0"
                />
              </group>
              <group name="Mid_part_3" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Mid_part_3_Interior_black_0'].geometry}
                  name="Mid_part_3_Interior_black_0"
                />
              </group>
              <group name="Right&Left_window_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Windows']}
                  geometry={nodes['Right&Left_window_2_Windows_0'].geometry}
                  name="Right&Left_window_2_Windows_0"
                />
              </group>
              <group name="Brake_light" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Taillight_glass']}
                  geometry={nodes['Brake_light_Taillight_glass_0'].geometry}
                  name="Brake_light_Taillight_glass_0"
                />
                <mesh
                  material={materials['Tail_light_brake']}
                  geometry={nodes['Brake_light_Tail_light_brake_0'].geometry}
                  name="Brake_light_Tail_light_brake_0"
                />
              </group>
              <group name="Right&Left_windows" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Windows']}
                  geometry={nodes['Right&Left_windows_Windows_0'].geometry}
                  name="Right&Left_windows_Windows_0"
                />
              </group>
              <group
                name="Wheel_FR"
                position={[-82.01, -122.59, 31.58]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[32.27, 32.27, 32.27]}>
                <mesh
                  material={materials['Tire']}
                  geometry={nodes['Wheel_FR_Tire_0'].geometry}
                  name="Wheel_FR_Tire_0"
                />
                <mesh
                  material={materials['Logo']}
                  geometry={nodes['Wheel_FR_Logo_0'].geometry}
                  name="Wheel_FR_Logo_0"
                />
                <mesh
                  material={materials['Caliper']}
                  geometry={nodes['Wheel_FR_Caliper_0'].geometry}
                  name="Wheel_FR_Caliper_0"
                />
                <mesh
                  material={materials['Brake_rotor']}
                  geometry={nodes['Wheel_FR_Brake_rotor_0'].geometry}
                  name="Wheel_FR_Brake_rotor_0"
                />
                <mesh
                  material={materials['material']}
                  geometry={nodes['Wheel_FR_Rim_0'].geometry}
                  name="Wheel_FR_Rim_0"
                />
              </group>
              <group
                name="Logo"
                position={[0, -214.07, 43.9]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[32.27, 30.35, 32.27]}>
                <mesh material={materials['Logo']} geometry={nodes['Logo_Logo_0'].geometry} name="Logo_Logo_0" />
              </group>
              <group name="Hood075" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Hood075_Plastic_0'].geometry}
                  name="Hood075_Plastic_0"
                />
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Hood075_Interior_black_0'].geometry}
                  name="Hood075_Interior_black_0"
                />
                <mesh
                  material={materials['Turning_light_right']}
                  geometry={nodes['Hood075_Turning_light_right_0'].geometry}
                  name="Hood075_Turning_light_right_0"
                />
                <mesh
                  material={materials['Turning_light_Left']}
                  geometry={nodes['Hood075_Turning_light_Left_0'].geometry}
                  name="Hood075_Turning_light_Left_0"
                />
                <mesh material={materials['Body']} geometry={nodes['Hood075_Body_0'].geometry} name="Hood075_Body_0" />
                <mesh
                  material={materials['Turning_light_inside']}
                  geometry={nodes['Hood075_Turning_light_inside_0'].geometry}
                  name="Hood075_Turning_light_inside_0"
                />
                <mesh
                  material={materials['Turning_light_glass']}
                  geometry={nodes['Hood075_Turning_light_glass_0'].geometry}
                  name="Hood075_Turning_light_glass_0"
                />
              </group>
              <group name="Interior_doors" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Interior_doors_Interior_black_0'].geometry}
                  name="Interior_doors_Interior_black_0"
                />
                <mesh
                  material={materials['Interior_color']}
                  geometry={nodes['Interior_doors_Interior_color_0'].geometry}
                  name="Interior_doors_Interior_color_0"
                />
              </group>
              <group name="Interior_general" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Interior_general_Interior_black_0'].geometry}
                  name="Interior_general_Interior_black_0"
                />
              </group>
              <group name="Interior_middle" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Interior_middle_Carbon_0'].geometry}
                  name="Interior_middle_Carbon_0"
                />
                <mesh
                  material={materials['Steering_wheel']}
                  geometry={nodes['Interior_middle_Steering_wheel_0'].geometry}
                  name="Interior_middle_Steering_wheel_0"
                />
              </group>
              <group name="Rear_window" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Windows']}
                  geometry={nodes['Rear_window_Windows_0'].geometry}
                  name="Rear_window_Windows_0"
                />
              </group>
              <group name="Interior_middle_parts" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Interior_middle_parts_Carbon_0'].geometry}
                  name="Interior_middle_parts_Carbon_0"
                />
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Interior_middle_parts_Interior_black_0'].geometry}
                  name="Interior_middle_parts_Interior_black_0"
                />
                <mesh
                  material={materials['Interior_color']}
                  geometry={nodes['Interior_middle_parts_Interior_color_0'].geometry}
                  name="Interior_middle_parts_Interior_color_0"
                />
                <mesh
                  material={materials['Start_button_lol']}
                  geometry={nodes['Interior_middle_parts_Start_button_lol_0'].geometry}
                  name="Interior_middle_parts_Start_button_lol_0"
                />
              </group>
              <group name="Seat" position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[59.27, 63.02, 63.02]}>
                <mesh
                  material={materials['Interior_color']}
                  geometry={nodes['Seat_Interior_color_0'].geometry}
                  name="Seat_Interior_color_0"
                />
                <mesh
                  material={materials['Interior_Black']}
                  geometry={nodes['Seat_Interior_Black_0'].geometry}
                  name="Seat_Interior_Black_0"
                />
              </group>
              <group name="Mid_part_2" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_Black']}
                  geometry={nodes['Mid_part_2_Interior_Black_0'].geometry}
                  name="Mid_part_2_Interior_Black_0"
                />
              </group>
              <group name="Mid_parts_1" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Plastic']}
                  geometry={nodes['Mid_parts_1_Plastic_0'].geometry}
                  name="Mid_parts_1_Plastic_0"
                />
              </group>
              <group name="Pedal" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh material={materials['Metal']} geometry={nodes['Pedal_Metal_0'].geometry} name="Pedal_Metal_0" />
              </group>
              <group
                name="Steering_wheel"
                position={[39.37, -45.89, 66.19]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[100, 100, 100]}>
                <mesh
                  material={materials['Logo']}
                  geometry={nodes['Steering_wheel_Logo_0'].geometry}
                  name="Steering_wheel_Logo_0"
                />
                <mesh
                  material={materials['Steering_wheel']}
                  geometry={nodes['Steering_wheel_Steering_wheel_0'].geometry}
                  name="Steering_wheel_Steering_wheel_0"
                />
              </group>
              <group name="Steering_wheel_holder" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Steering_wheel_holder_Interior_black_0'].geometry}
                  name="Steering_wheel_holder_Interior_black_0"
                />
              </group>
              <group name="Speedometer" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Interior_black']}
                  geometry={nodes['Speedometer_Interior_black_0'].geometry}
                  name="Speedometer_Interior_black_0"
                />
                <mesh
                  material={materials['Cluster']}
                  geometry={nodes['Speedometer_Cluster_0'].geometry}
                  name="Speedometer_Cluster_0"
                />
              </group>
              <group name="Mirrors" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Carbon']}
                  geometry={nodes['Mirrors_Carbon_0'].geometry}
                  name="Mirrors_Carbon_0"
                />
                <mesh material={materials['Body']} geometry={nodes['Mirrors_Body_0'].geometry} name="Mirrors_Body_0" />
                <mesh
                  material={materials['mirror']}
                  geometry={nodes['Mirrors_mirror_0'].geometry}
                  name="Mirrors_mirror_0"
                />
              </group>
              <group
                name="Wheel_BR"
                position={[-80.48, 134.16, 34.72]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[34.78, 34.78, 34.78]}>
                <mesh
                  material={materials['Tire']}
                  geometry={nodes['Wheel_BR_Tire_0'].geometry}
                  name="Wheel_BR_Tire_0"
                />
                <mesh
                  material={materials['Logo']}
                  geometry={nodes['Wheel_BR_Logo_0'].geometry}
                  name="Wheel_BR_Logo_0"
                />
                <mesh
                  material={materials['Caliper']}
                  geometry={nodes['Wheel_BR_Caliper_0'].geometry}
                  name="Wheel_BR_Caliper_0"
                />
                <mesh
                  material={materials['Brake_rotor']}
                  geometry={nodes['Wheel_BR_Brake_rotor_0'].geometry}
                  name="Wheel_BR_Brake_rotor_0"
                />
                <mesh
                  material={materials['material']}
                  geometry={nodes['Wheel_BR_Rim_0'].geometry}
                  name="Wheel_BR_Rim_0"
                />
              </group>
              <group
                name="Wheel_FL"
                position={[82.01, -122.59, 31.58]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[100, 100, 100]}>
                <mesh
                  material={materials['Tire']}
                  geometry={nodes['Wheel_FL_Tire_0'].geometry}
                  name="Wheel_FL_Tire_0"
                />
                <mesh
                  material={materials['Logo']}
                  geometry={nodes['Wheel_FL_Logo_0'].geometry}
                  name="Wheel_FL_Logo_0"
                />
                <mesh
                  material={materials['Caliper']}
                  geometry={nodes['Wheel_FL_Caliper_0'].geometry}
                  name="Wheel_FL_Caliper_0"
                />
                <mesh
                  material={materials['Brake_rotor']}
                  geometry={nodes['Wheel_FL_Brake_rotor_0'].geometry}
                  name="Wheel_FL_Brake_rotor_0"
                />
                <mesh
                  material={materials['material']}
                  geometry={nodes['Wheel_FL_Rim_0'].geometry}
                  name="Wheel_FL_Rim_0"
                />
              </group>
              <group
                name="Wheel_BL"
                position={[80.48, 134.16, 34.72]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[100, 100, 100]}>
                <mesh
                  material={materials['Tire']}
                  geometry={nodes['Wheel_BL_Tire_0'].geometry}
                  name="Wheel_BL_Tire_0"
                />
                <mesh
                  material={materials['Logo']}
                  geometry={nodes['Wheel_BL_Logo_0'].geometry}
                  name="Wheel_BL_Logo_0"
                />
                <mesh
                  material={materials['Caliper']}
                  geometry={nodes['Wheel_BL_Caliper_0'].geometry}
                  name="Wheel_BL_Caliper_0"
                />
                <mesh
                  material={materials['Brake_rotor']}
                  geometry={nodes['Wheel_BL_Brake_rotor_0'].geometry}
                  name="Wheel_BL_Brake_rotor_0"
                />
                <mesh
                  material={materials['material']}
                  geometry={nodes['Wheel_BL_Rim_0'].geometry}
                  name="Wheel_BL_Rim_0"
                />
              </group>
              <group name="Rear_engine_carbon_vents" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Vents']}
                  geometry={nodes['Rear_engine_carbon_vents_Vents_0'].geometry}
                  name="Rear_engine_carbon_vents_Vents_0"
                />
              </group>
              <group name="Rear_part_3001" rotation={[0, 0, -Math.PI / 2]} scale={[100, 100, 100]}>
                <mesh
                  material={materials['Taillight_rear']}
                  geometry={nodes['Rear_part_3001_Taillight_rear_0'].geometry}
                  name="Rear_part_3001_Taillight_rear_0"
                />
              </group>
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
