// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import Car2 from "../../public/model_3d/Car/Car1/porsche_911_c4s_2020_aerokit.glb"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, Car2)

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={[2.5, 2.5, 2.5]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Shape001_0">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_4'].geometry}
                  name="Object_4"
                />
              </group>
              <group name="Plane001_1">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_6'].geometry}
                  name="Object_6"
                />
              </group>
              <group name="Body001_2">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_8'].geometry}
                  name="Object_8"
                />
              </group>
              <group name="wheel_Tires001_3">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_10'].geometry}
                  name="Object_10"
                />
              </group>
              <group name="Metal_Parts001_4">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_12'].geometry}
                  name="Object_12"
                />
              </group>
              <group name="logo_002_5">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_14'].geometry}
                  name="Object_14"
                />
              </group>
              <group name="interior_Parts001_6">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_16'].geometry}
                  name="Object_16"
                />
              </group>
              <group name="Glass_Parts001_7">
                <mesh material={materials['glass']} geometry={nodes['Object_18'].geometry} name="Object_18" />
              </group>
              <group name="Glass_Lights001_8">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_20'].geometry}
                  name="Object_20"
                />
              </group>
              <group name="Floor_Part001_9" rotation={[0, 0, 0]}>
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_22'].geometry}
                  name="Object_22"
                />
              </group>
              <group name="Mirrors001_10">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_24'].geometry}
                  name="Object_24"
                />
              </group>
              <group name="PVC_parts001_11">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_26'].geometry}
                  name="Object_26"
                />
              </group>
              <group name="Object001_12">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_28'].geometry}
                  name="Object_28"
                />
              </group>
              <group name="Object002_13">
                <mesh
                  material={materials['Porsche_911_C4S_2020_Aerokit']}
                  geometry={nodes['Object_30'].geometry}
                  name="Object_30"
                />
              </group>
              <group name="Object003_14">
                <mesh material={materials['glass']} geometry={nodes['Object_32'].geometry} name="Object_32" />
              </group>
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
